/*
 * Ported from OptiFabric (https://github.com/Chocohead/OptiFabric), MPL-2.0.
 * Adapted for Minecraft 1.20.6 / Fabric Loader 0.19.x.
 *
 * Changes from upstream:
 *   - no Fabric-ASM / com.chocohead.mm dependency (the jar is handed to Fabric Loader instead);
 *   - tiny-remapper is taken from the copy Fabric Loader ships (relocated to
 *     net.fabricmc.loader.impl.lib.tinyremapper), so nothing extra has to be bundled;
 *   - the mappings come from the intermediary mappings bundled into this jar by the build;
 *   - development environments (runtime namespace "named") are refused with a clear message instead
 *     of being remapped through the extra contextual mapping layer upstream needed for them.
 */
package kynarain.cn.optifabric.mod;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.function.Consumer;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipException;
import java.util.zip.ZipFile;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.tree.ClassNode;

import net.fabricmc.loader.api.FabricLoader;
import net.fabricmc.loader.impl.launch.FabricLauncherBase;

import net.fabricmc.loader.impl.lib.mappingio.MappingReader;
import net.fabricmc.loader.impl.lib.mappingio.tree.MemoryMappingTree;
import net.fabricmc.loader.impl.lib.tinyremapper.IMappingProvider;
import net.fabricmc.loader.impl.lib.tinyremapper.InputTag;
import net.fabricmc.loader.impl.lib.tinyremapper.NonClassCopyMode;
import net.fabricmc.loader.impl.lib.tinyremapper.OutputConsumerPath;
import net.fabricmc.loader.impl.lib.tinyremapper.TinyRemapper;
import net.fabricmc.loader.impl.lib.tinyremapper.TinyUtils;
import net.fabricmc.loader.impl.lib.tinyremapper.api.TrLogger;

import kynarain.cn.optifabric.mod.OptifineVersion.JarType;
import kynarain.cn.optifabric.patcher.ClassCache;
import kynarain.cn.optifabric.patcher.LambdaRebuilder;
import kynarain.cn.optifabric.util.ASMUtils;
import kynarain.cn.optifabric.util.ZipUtils;
import kynarain.cn.optifabric.util.ZipUtils.ZipTransformer;
import kynarain.cn.optifabric.util.ZipUtils.ZipVisitor;

/**
 * Turns the OptiFine jar from the mods folder into something Fabric can run:
 * runs the OptiFine patcher over the vanilla (obfuscated) Minecraft jar, fixes up lambdas, remaps
 * everything from the official namespace to intermediary, and splits the result into
 * <ul>
 *   <li>a jar with OptiFine's own classes and resources, which goes on the game classpath, and</li>
 *   <li>a cache of patched Minecraft classes, which replace the game's version at class load time.</li>
 * </ul>
 * Both are cached in {@code .optifine/<version>/} inside the game directory.
 */
public class OptifineSetup {
	public static OptifineRuntime getRuntime() throws IOException {
		File workingDir = new File(FabricLoader.getInstance().getGameDirectory(), ".optifine");
		if (!workingDir.exists() && !workingDir.mkdirs()) throw new IOException("Failed to create " + workingDir);

		File optifineModJar = OptifineVersion.findOptifineJar();
		byte[] modHash = md5(optifineModJar);

		File versionDir = new File(workingDir, OptifineVersion.version);
		if (!versionDir.exists() && !versionDir.mkdirs()) throw new IOException("Failed to create " + versionDir);

		File remappedJar = new File(versionDir, "Optifine-mapped.jar");
		File optifinePatches = new File(versionDir, "Optifine.classes.gz");
		File cacheStamp = new File(versionDir, "cache-format.txt");

		//Artifacts produced by an older pipeline must not be reused: the cache format is bumped whenever
		//the generated bytes would change (e.g. stack map frames no longer being dropped).
		boolean cacheUsable = remappedJar.exists() && optifinePatches.exists() && cacheStamp.exists()
				&& String.valueOf(CACHE_FORMAT).equals(Files.readString(cacheStamp.toPath(), StandardCharsets.UTF_8).trim());

		if (cacheUsable) {
			ClassCache classCache = ClassCache.read(optifinePatches);

			//Validate that the classCache found is for the same input jar
			if (Arrays.equals(classCache.getHash(), modHash)) {
				System.out.println("[OptiFabric] Found existing patched OptiFine jar, using that");

				if (classCache.isConverted()) {
					classCache.save(optifinePatches);
				}

				return new OptifineRuntime(remappedJar.toPath(), classCache);
			} else {
				System.out.println("[OptiFabric] Class cache is from a different OptiFine jar, deleting and re-generating");
			}
		} else {
			if (remappedJar.exists() || optifinePatches.exists()) {
				System.out.println("[OptiFabric] Patched OptiFine cache is from an older OptiFabric, regenerating it");
			} else {
				System.out.println("[OptiFabric] Setting up OptiFine for the first time, this may take a few seconds.");
			}
		}

		String namespace = FabricLoader.getInstance().getMappingResolver().getCurrentRuntimeNamespace();

		if (!"intermediary".equals(namespace)) {
			throw new IllegalStateException("OptiFabric can currently only load OptiFine in a production runtime"
					+ " (namespace \"intermediary\"), but this instance runs in the \"" + namespace + "\" namespace.\n"
					+ "Run the built OptiFabric jar in a normal launcher with Fabric Loader and OptiFine 1.20.6 in the"
					+ " mods folder instead of launching it from a development environment.");
		}

		Path minecraftJar = getMinecraftJar();
		File workDir = Files.createTempDirectory("optifabric").toFile();

		if (OptifineVersion.jarType == JarType.OPTIFINE_INSTALLER) {
			File optifineMod = new File(workDir, "Optifine-mod.jar");

			out: if (!optifineMod.exists() || !ZipUtils.isValid(optifineMod)) {
				for (int attempt = 1; attempt <= 3; attempt++) {
					runInstaller(optifineModJar, optifineMod, minecraftJar.toFile());

					if (!ZipUtils.isValid(optifineMod)) {
						optifineMod.delete();
						continue;
					}

					break out; //Produced a valid extracted jar
				}

				OptifineVersion.jarType = JarType.CORRUPT_ZIP;
				OptifabricError.setError("OptiFine installer keeps producing corrupt jars!\nRan: %s 3 times\nMinecraft jar: %s", optifineModJar, minecraftJar);
				throw new ZipException("Ran OptiFine installer (" + optifineModJar + ") three times without a valid jar produced");
			}

			optifineModJar = optifineMod;
		}

		//A jar without srgs
		File jarOfTheFree = new File(workDir, "Optifine-jarofthefree.jar");
		LambdaRebuilder rebuilder = new LambdaRebuilder(minecraftJar.toFile());

		System.out.println("[OptiFabric] De-Volderfiying jar");

			try {
			//Find all the SRG named classes and remove them
			ZipUtils.transform(optifineModJar, new ZipTransformer() {
				@Override
				public String mapName(ZipEntry entry) {
					String out = entry.getName();
					return out.startsWith("notch/") ? out.substring(6) : out;
				}

				@Override
				public InputStream apply(ZipFile zip, ZipEntry entry) throws IOException {
					String name = entry.getName();

					if (!name.startsWith("srg/")) {
						if (name.endsWith(".class") && !name.startsWith("net/") && !name.startsWith("notch/net/") && !name.startsWith("optifine/") && !name.startsWith("javax/")) {
							//The patched Minecraft classes: their lambdas point at the original methods, which moved.
							//Frames have to be read expanded - they are what keeps these classes verifiable once the
							//game loads them. Upstream read them with SKIP_FRAMES, which was harmless only because
							//Mixin happened to recompute the frames when it rewrote the class.
							ClassNode node = readClassWithFrames(zip, entry);
							rebuilder.findLambdas(node);

							ClassWriter writer = new ClassWriter(0);
							node.accept(writer);
							return new ByteArrayInputStream(writer.toByteArray());
						} else {
							return zip.getInputStream(entry);
						}
					} else {
						return null;
					}
				}
			}, jarOfTheFree);
			} finally {
				rebuilder.close(); //Always: it holds the vanilla jar and its scratch files open.
			}
		rebuilder.close();
		System.out.println("[OptiFabric] Remapping OptiFine from official to " + namespace);
		File completeJar = new File(workDir, "Optifine-remapped.jar");
		remapOptifine(jarOfTheFree, getLibs(), completeJar, createMappings("official", namespace));

		File completedJar = completeJar;

		Consumer<ZipVisitor> jarFinaliser;
		if (remappedJar.exists() && !remappedJar.delete()) {
			System.err.println("[OptiFabric] Failed to clear " + remappedJar + ", is another instance of the game running?");
			remappedJar = completedJar;
			jarFinaliser = visitor -> ZipUtils.filterInPlace(completedJar, visitor);
		} else {
			final File finalRemappedJar = remappedJar; //It's final in this code path... but javac knows it's not final everywhere
			jarFinaliser = visitor -> ZipUtils.filter(completedJar, visitor, finalRemappedJar);
		}

		if (optifinePatches.exists() && !optifinePatches.delete()) {
			System.err.println("[OptiFabric] Failed to clear " + optifinePatches + ", is another instance of the game running?");
			optifinePatches = new File(workDir, "Optifine.classes.gz");
		}

		//We are done, lets get rid of the stuff we no longer need
		workDir.deleteOnExit();
		File[] leftOvers = workDir.listFiles();
		if (leftOvers != null) for (File file : leftOvers) file.deleteOnExit();

		boolean extract = Boolean.getBoolean("optifabric.extract");
		if (extract) {
			System.out.println("[OptiFabric] Extracting OptiFine classes");
			File optifineClasses = new File(versionDir, "optifine-classes");
			if (optifineClasses.exists()) {
				deleteRecursively(optifineClasses);
			}
			ZipUtils.extract(completedJar, optifineClasses);
		}

		ClassCache generated = generateClassCache(jarFinaliser, optifinePatches, modHash, extract);
		Files.writeString(cacheStamp.toPath(), String.valueOf(CACHE_FORMAT), StandardCharsets.UTF_8);

		return new OptifineRuntime(remappedJar.toPath(), generated);
	}

	/** Bumped whenever the cached artifacts would come out different, so stale caches regenerate themselves. */
	private static final int CACHE_FORMAT = 2;

	/** Reads a class with its stack map frames expanded, so they survive the round trip (see the de-volderfy step). */
	private static ClassNode readClassWithFrames(ZipFile zip, ZipEntry entry) throws IOException {
		try (InputStream in = zip.getInputStream(entry)) {
			ClassNode node = new ClassNode();
			new ClassReader(in).accept(node, ClassReader.EXPAND_FRAMES);

			return node;
		}
	}

	private static void runInstaller(File installer, File output, File minecraftJar) throws IOException {
		System.out.println("[OptiFabric] Running OptiFine patcher");

		try (URLClassLoader classLoader = new URLClassLoader(new URL[] {installer.toURI().toURL()}, OptifineSetup.class.getClassLoader())) {
			Class<?> clazz = classLoader.loadClass("optifine.Patcher");
			Method method = clazz.getDeclaredMethod("process", File.class, File.class, File.class);
			method.invoke(null, minecraftJar, installer, output);
		} catch (ReflectiveOperationException e) {
			throw new RuntimeException("Error running OptiFine patcher at " + installer + " on " + minecraftJar, e);
		}
	}

	private static void remapOptifine(File input, Path[] libraries, File output, IMappingProvider mappings) throws IOException {
		Files.deleteIfExists(output.toPath());

		TrLogger logger = (level, message) -> System.out.println("[OptiFabric/remap] " + level + ": " + message);

		TinyRemapper remapper = TinyRemapper.newRemapper(logger)
				.withMappings(mappings)
				.renameInvalidLocals(false)
				.rebuildSourceFilenames(true)
				.build();

		InputTag tag = remapper.createInputTag();

		try (OutputConsumerPath outputConsumer = new OutputConsumerPath.Builder(output.toPath()).assumeArchive(true).build()) {
			outputConsumer.addNonClassFiles(input.toPath(), NonClassCopyMode.UNCHANGED, remapper);
			remapper.readInputsAsync(tag, input.toPath());
			remapper.readClassPathAsync(libraries);

			remapper.apply(outputConsumer, tag);
		} catch (Exception e) {
			throw new RuntimeException("Failed to remap jar", e);
		} finally {
			remapper.finish();
		}
	}

	/** Official (obfuscated) to the runtime namespace, using the mappings bundled into this jar by the build. */
	private static IMappingProvider createMappings(String from, String to) {
		return OptifineMappings.provider(from, to);
	}

	/** The launch classpath, which is in the official namespace and so is exactly what the remapper needs. */
	private static Path[] getLibs() {
		return FabricLauncherBase.getLauncher().getClassPath().stream().filter(Files::exists).toArray(Path[]::new);
	}

	/** The official (obfuscated) Minecraft client jar, which is what OptiFine's patcher expects. */
	private static Path getMinecraftJar() {
		String givenJar = System.getProperty("optifabric.mc-jar");
		if (givenJar != null) {
			File givenJarFile = new File(givenJar);

			if (givenJarFile.exists()) {
				return givenJarFile.toPath();
			} else {
				System.err.println("[OptiFabric] Supplied Minecraft jar at " + givenJar + " doesn't exist, falling back");
			}
		}

		Object single = FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJar");
		if (single instanceof Path path && Files.exists(path)) return path;

		Object all = FabricLoader.getInstance().getObjectShare().get("fabric-loader:inputGameJars");
		if (all instanceof List<?> list && !list.isEmpty() && list.get(0) instanceof Path path && Files.exists(path)) return path;

		throw new IllegalStateException("Unable to find the Minecraft jar OptiFine has to be patched into."
				+ " Please supply it explicitly with -Doptifabric.mc-jar=<path to the vanilla 1.20.6 client jar>");
	}

	private static ClassCache generateClassCache(Consumer<ZipVisitor> from, File to, byte[] hash, boolean extractClasses) throws IOException {
		File classesDir = new File(to.getParent(), "classes");
		if (extractClasses) {
			if (classesDir.exists()) {
				deleteRecursively(classesDir);
			} else if (!classesDir.mkdirs()) {
				throw new IOException("Failed to create " + classesDir);
			}
		}
		ClassCache classCache = new ClassCache(hash);

		from.accept((jarFile, entry) -> {
			String name = entry.getName();

			if ((name.startsWith("net/minecraft/") || name.startsWith("com/mojang/")) && name.endsWith(".class")) {
				byte[] bytes;
				try (InputStream in = jarFile.getInputStream(entry)) {
					bytes = in.readAllBytes();
				}

				classCache.addClass(name.substring(0, name.length() - 6), bytes);
				if (extractClasses) {
					File extract = new File(classesDir, name);
					File parent = extract.getParentFile();
					if (parent != null) parent.mkdirs();
					Files.write(extract.toPath(), bytes);
				}

				return false; //Remove all the patched classes, we don't want these leaking directly on the classpath
			} else {
				return true;
			}
		});

		System.out.println("[OptiFabric] Found " + classCache.getClasses().size() + " patched classes");
		classCache.save(to);
		return classCache;
	}

	private static byte[] md5(File file) throws IOException {
		try (InputStream in = new FileInputStream(file)) {
			return MessageDigest.getInstance("MD5").digest(in.readAllBytes());
		} catch (NoSuchAlgorithmException e) {
			throw new IllegalStateException("MD5 is unavailable", e);
		}
	}

	private static void deleteRecursively(File root) throws IOException {
		Path path = root.toPath();

		if (!Files.exists(path)) return;

		try (Stream<Path> files = Files.walk(path)) {
			files.sorted(Comparator.reverseOrder()).forEach(p -> {
				try {
					Files.deleteIfExists(p);
				} catch (IOException e) {
					throw new UncheckedIOException(e);
				}
			});
		}
	}
}
